services:
  app:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: api-places
      DB_USERNAME: root
      DB_PASSWORD: mysecretpassword

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: api-places
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
